version: "3.9"
services:
  app:
    container_name: django_app
    restart: always
    image: bisratberhanu/flower_classifier:django_app
    ports:
      - 8070:8000
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

